# landscape short name use slug from PCC
landscapeName: camarafund
# Update with your membership structure
landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
# SF Project record ID for your project
project: a092M00001MtYMaQAN # CAMARA Fund
# Name of category for members 
landscapeMemberCategory: CAMARA Fund Member Company
